# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://azurebootcamp.ch/"

languageCode = "en"
defaultContentLanguage = "en"
theme = ["congo", "hugo-shortcode-gallery"]

title = "Azure Bootcamp Switzerland"
description = "Azure Bootcamp Switzerland is a 100% community-driven one-day conference around Microsoft Azure Cloud Computing platform in Switzerland"

enableEmoji = true
enableRobotsTXT = true

summaryLength = 0

# Increase timeout because of image processing
timeout = 120000