# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "congo"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = false
# logo = "img/logo.png"
# description = "My awesome website"
# mainSections = ["section1", "section2"]
# robots = ""

[homepage]
  layout = "page" # valid options: page, profile, custom
  showRecent = false

[article]
  showDate = false
  dateFormat = "2 January 2006"
  showAuthor = false
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = false
  showReadingTime = false
  # sharingLinks = ["facebook", "twitter", "pinterest", "reddit", "linkedin", "email"]

[list]
  showBreadcrumbs = true
  showSummary = false
  groupByYear = false

[taxonomy]
  showTermCount = true

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[footer]
  showAppearanceSwitcher = true
  showCopyright = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
